name: Tests

on:
  pull_request:
  push:

env:
  ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
  ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  tests:
    name: Run tests (${{ matrix.image }})

    # prevent workflow jobs run twice on push and pull_request event
    # see https://github.com/orgs/community/discussions/57827
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    strategy:
      fail-fast: false
      matrix:
        include:
          - image: 1.6.6-erlang-21.3.8.24-debian-buster-20210902-slim
          - image: 1.19.3-erlang-28.1.1-debian-bullseye-20251103-slim

    runs-on: ubuntu-latest
    container:
      image: hexpm/elixir:${{ matrix.image }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Hex and Rebar setup
      run: |
        mix local.hex --force
        mix local.rebar --force

    - name: Restore deps and _build cache
      uses: actions/cache@v4
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.image }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.image }}

    - name: Install dependencies
      run: mix deps.get --only test

    - name: Run tests
      run: |
        epmd -daemon
        mix test
